### ISSUE TITLE
syntax error fn_stopServer

### ISSUE THREAD

**Issue by joka-de** [joka-de/slass#12]
/home/slad/slasstesting/slass-data/function/slass/fn_stopServer.sh: line 1: syntax error near unexpected token `$'{\r''
'home/slad/slasstesting/slass-data/function/slass/fn_stopServer.sh: line 1: `fn_stopServer () {

**Comment by PhilipJFryy** [comment]
Make sure the line endings are LF (Unix) not CRLF (Windows)

[https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings](url)

**Comment by joka-de** [comment]
solved ... :D
