### ISSUE TITLE
wrong config file / server id (1) being read

### ISSUE THREAD

**Issue by joka-de** [joka-de/slass#19]
Maybe a leftover from testing ...
the name of the json config is server.json - right?

fn_mkaconfig:
line 19 "1"
line 24 a3srv${1}
line 37 ${basepath}/config/serverSml.json
line 88 local hostname=$(fn_getJSONData "$1" "slass.hostname" "-r")

possible issue: line 35 - is "basic.cfg" not replaced by json entries?

fn_getJSONData:
line 29 local serverFile="${basepath}/config/serverSml.json"

am too afraid to fix your code

**Comment by PhilipJFryy** [comment]
Yes. It must be server.json

**Comment by PhilipJFryy** [comment]
I has fixed IT a few days ago in GitHub.
