### ISSUE TITLE
no needed mods shown on arma

### ISSUE THREAD

**Issue by alexm16** [joka-de/slass#3]
Hey awesome scripts. One Thing I dont seem to find out, is I have many client/server mods. But none show on the arma launcher.
https://gyazo.com/d6fcdc1f616979f072a51d2b6ca582a1
Thanks for your help

**Comment by joka-de** [comment]
Hey alex, 
sorry for my late response, hope i can help still. Thank you for the nice words on the scripts.
I guess your screenshot is from the ingame browser, which I never used this and so cannot tell if it actually works. My explanations refer to the browser in the launcher.
Your issue could have various reasons. Check your file "modlist.inp" for the scheme, example:

cba_a3 450814997 mod 0 0 1 CBA

cba_a3 - internal mod name used in the file structure of slass
4508... - workshop id
mod - type of mod (this column is important);
- mod - mod is run on client and server, the keyfile is loaded on the server (enforces client to load the mod, i.e. lists the mod in browser)
- cmod - client only mod, only keyfile is loaded on the server, client MAY load the mod (optional mod)
- smod - mod runs on server only, no keyfile used

0 0 1 - server where mod runs
CBA - name of the mod shown in the Server NAME, xx to show no name

We recently had an issue with RHS causing the behaviour you described, but never found out the cause. Problem solved itself after a few days.

**Comment by joka-de** [comment]
assumed as resolved
